runtime:    python
env:        flex
entrypoint: uvicorn --port $PORT  main:app
service:    fastapi

runtime_config:
  python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

resources:
  cpu: 2
  memory_gb: 1.4

network:
  name: vpc-va-ivr
  subnetwork_name: sbn-va-ivr-eu

handlers:
  - url: /.*
    script: auto
    secure: always